"""Initial migration

Revision ID: 9b8c0e4ab153
Revises: e6fe1251db27
Create Date: 2021-06-09 13:51:13.021085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8c0e4ab153'
down_revision = 'e6fe1251db27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_likes', sa.Column('answer_id', sa.Integer(), nullable=True))
    op.drop_constraint('answer_likes_post_id_fkey', 'answer_likes', type_='foreignkey')
    op.create_foreign_key(None, 'answer_likes', 'answers', ['answer_id'], ['id'])
    op.drop_column('answer_likes', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_likes', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answer_likes', type_='foreignkey')
    op.create_foreign_key('answer_likes_post_id_fkey', 'answer_likes', 'answers', ['post_id'], ['id'])
    op.drop_column('answer_likes', 'answer_id')
    # ### end Alembic commands ###
